name: Build and publish a Hex package

on:
  push:
    tags:
      - v*

jobs:
  publish:

    env:
      MIX_ENV: test

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get versions
      run: |
        echo "ELIXIR_VERSION=$(grep -h elixir .tool-versions | awk '{ print $2 }' | awk -F - '{print $1}')" >> $GITHUB_ENV
        echo "OTP_VERSION=$(grep -h erlang .tool-versions | awk '{ print $2 }')" >> $GITHUB_ENV

    - name: Setup Elixir and Erlang versions
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ env.ELIXIR_VERSION }}
        otp-version: ${{ env.OTP_VERSION }}

    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get

    - name: Check code formatting
      run: mix format --check-formatted

    - name: Compile deps
      run: mix deps.compile

    - name: Run Tests
      run: mix test

    - name: Check code quality
      run: mix credo

    - name: Generate documentation
      run: mix docs

    - name: Build package
      run: mix hex.build

    - name: Determine app version
      env:
        GITHUB_REF: ${{ github.ref }}
      run: echo "APP_VERSION=$(echo "$GITHUB_REF" | awk -F / '{print $3}')" >> $GITHUB_ENV

    - name: Set app version
      run: echo $APP_VERSION > .app_version

    - name: Publish package
      run: mix hex.publish --yes
      env:
        HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
